# data process
shuffle:              False
num_of_cpu_workers:   12

# Z-blocks structure
L: 3
K: 5

# model structure
hidden_neurons:       50

# training parameters
custom_loss:          True
la:                   0.5
batch_size:           1
epochs:               50
learn_rate:           1e-3
weight_decay:         1e-4

